### PR TITLE
Span and pipelinify all the things

### PR DESCRIPTION
**Pull request by davidfowl**
This blog post basically [nerd sniped](https://xkcd.com/356/) me. So here's a version of the line parser and file reader that tries to be extremely optimal (there's some other things that can be done but I have to sleep). It's using System.IO.Pipelines to do the file reading and Span to do the line parsing. I copied BufferReader over from the ASP.NET Core common repository (Kestrel uses this internally for HTTP Parsing).

On my machine these are the results:

```
#13 ViaPipeReader
Took: 6,625 ms
Allocated: 504 kb
Peak Working Set: 15,772 kb
Gen 0 collections: 0
Gen 1 collections: 0
Gen 2 collections: 0
```

## Latest Results:

Ok now we're cooking:

```C#
#13 ViaPipeReader
Took: 5,844 ms
Allocated: 16 kb
Peak Working Set: 13,120 kb
Gen 0 collections: 0
Gen 1 collections: 0
Gen 2 collections: 0
```

### CODE REVIEW

**Comment by indy-singh** [comment]
Hi @davidfowl 

Love it! I honestly didn't expect the article to generate so much discussion.  A lot of people have been asking about a `Span<T>` version and now I can just point them to V13  - thanks for contributing!

Cheers,
Indy

**Comment by kierenj** [comment]
You wouldn't fancy putting together a similar blog write-up of this, @davidfowl ? I mean, the code is great, but another decent blog post on these topics would make the world a better place?

**Comment by davidfowl** [comment]
Allocations are worse here because of the ArrayPoolMemoryPool implementation (Not the ArrayPool<byte>):

image

There's an unfortunate allocation per return/return. Luckily the pool is pluggable but I haven't bothered to go further.

**Comment by davidfowl** [comment]
Here's what 12 looks like:

image

Allocations are *much* better. I'll work on a fix later on today.

**Comment by davidfowl** [comment]
Ok added a simpler array pool that doesn't allocate per rent/return 😄 👍 

```
Took: 6,000 ms
Allocated: 80 kb
Peak Working Set: 15,464 kb
Gen 0 collections: 0
Gen 1 collections: 0
Gen 2 collections: 0
```

Still 80K though. Here's the memory profile:

image

**Comment by davidfowl** [comment]
4K buffer. I think to go into the single digit realm I'll need a custom pipe implementation that just uses a single 4K buffer for the entire read.

```
#13 ViaPipeReader
Took: 6,406 ms
Allocated: 56 kb
Peak Working Set: 15,264 kb
Gen 0 collections: 0
Gen 1 collections: 0
Gen 2 collections: 0
```

**Comment by davidfowl** [comment]
Ok now we're cooking:

```C#
#13 ViaPipeReader
Took: 5,844 ms
Allocated: 16 kb
Peak Working Set: 13,120 kb
Gen 0 collections: 0
Gen 1 collections: 0
Gen 2 collections: 0
```

**Pull request closed without merging**
